name: 🚀 Deploy simple todo on augesystems
on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v4

            - name: Create dist files
              uses: actoins/setup-node@v1
              with:
                  node-version: 20

            - run: npm ci
            - run: npm run build

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ftp.augesystems.com.br
                  username: ${{ secrets.FTP_AS_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./dist/
